---
- name: Configure EC2 instance for Flask app
  hosts: localhost
  become: true

  vars:
    docker_compose_version: "1.29.2"
    repo_url: "https://github.com/Ariel-ksenzovsky/Jenkins-docker-pipeline.git"
    s3_bucket: "my-bucket101110101"
    s3_env_path: "configs/.env"

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - git
          - docker
          - libxcrypt-compat
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Clone the Flask app repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/ec2-user/Jenkins-docker-pipeline
        version: HEAD

    - name: Copy the .env file from S3
      command: aws s3 cp s3://{{ s3_bucket }}/{{ s3_env_path }} /home/ec2-user/Jenkins-docker-pipeline/.env
      args:
        creates: /home/ec2-user/Jenkins-docker-pipeline/.env

    - name: Run Docker Compose to start the application
      shell: |
        docker-compose up
      args:
        chdir: /home/ec2-user/Jenkins-docker-pipeline
