---
- name: Configure EC2 instance for Flask app
  hosts: localhost
  become: true

  vars:
    repo_url: "https://github.com/Ariel-ksenzovsky/Jenkins-docker-pipeline.git"
    s3_bucket: "my-bucket101110101"

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - git
          - docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Clone the Flask app repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/ec2-user/Jenkins-docker-pipeline
        version: HEAD

    - name: Run Docker Compose to start the application
      shell: |
        docker run -d arielk2511/weather-app --name flask-app -p 5000:5000
      args:
        chdir: /home/ec2-user/Jenkins-docker-pipeline
